spring.application.name=book-recommendation
server.port=8080

app.rdf.file=data/books.rdf

app.llm.api-url=https://openrouter.ai/api/v1/chat/completions
app.llm.api-key=API_KEY
app.llm.model=openai/gpt-4o-mini

app.vectordb.dimension=384

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
